### ISSUE TITLE
Sonatype Report tab fails to ever render results when running Nexus Lifecycle > 121

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/teamcity-nexusiq-plugin#19]
Nexus Lifecycle 122+ appears to have changed the data model for the results.json output using the Nexus IQ CLI causing the Team City plugin to fails to parse the results.json file which leads to a blank Sonatype Report tab.

Exceptions can be see in Team City server similar to:
```
[2021-09-07 08:50:25,158]   WARN [@62b1caa4'; Normal executor 13] -    jetbrains.buildServer.AGENT - Agent "Linux Agent-1" {id=2} is unauthorized on registration
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "packageId" (class org.sonatype.teamcity.results.Coordinates), not marked as ignorable (7 known properties: "classifier", "version", "groupID", "name", "artifactID", "extension", "qualifier"])
 at [Source: (StringReader); line: 175, column: 30] (through reference chain: org.sonatype.teamcity.results.IQScanResult["policyEvaluationResult"]->org.sonatype.teamcity.results.PolicyEvaluationResult["alerts"]->java.lang.Object[][3]->org.sonatype.teamcity.results.Alert["trigger"]->org.sonatype.teamcity.results.Trigger["componentFacts"]->java.lang.Object[][0]->org.sonatype.teamcity.results.ComponentFact["componentIdentifier"]->org.sonatype.teamcity.results.ComponentIdentifier["coordinates"]->org.sonatype.teamcity.results.Coordinates["packageId"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
...
```

FYI @hboutemy

**Comment by hboutemy** [comment]
trying to reproduce, this is a new field for some component ecosystem:
```
          "componentIdentifier" : {
            "format" : "a-name",
            "coordinates" : {
              "name" : "org.webjars bootstrap",
              "qualifier" : "",
              "version" : "3.1.1"
            }
          },
```

notice that I could not find which format it was: can you provide a failure example, please?

**Comment by madpah** [comment]
Hey @hboutemy - afraid I don't have the exact example any longer, but it was NPM or NuGet I believe from memory. Will keep digging to see if I can find the exact example.

**Comment by madpah** [comment]
Found it @hboutemy - it was NPM:

```
"componentIdentifier" : {
            "format" : "npm",
            "coordinates" : {
              "packageId" : "bootstrap",
              "version" : "3.3.7"
            }
          },
```
